//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="SweaWebServiceSoap12Binding", Namespace="http://swea.riksbank.se/ws")]
public partial class SweaWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getInterestAndExchangeNamesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getMonthlyAverageExchangeRatesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getInterestAndExchangeGroupNamesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getCrossRatesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getAllCrossNamesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getCalendarDaysOperationCompleted;
    
    private System.Threading.SendOrPostCallback getAnnualAverageExchangeRatesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getInterestAndExchangeRatesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getLatestInterestAndExchangeRatesOperationCompleted;
    
    /// <remarks/>
    public SweaWebService() {
        this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
        this.Url = "https://swea.riksbank.se:443/sweaWS/services/SweaWebServiceHttpSoap12Endpoint";
    }
    
    /// <remarks/>
    public event getInterestAndExchangeNamesCompletedEventHandler getInterestAndExchangeNamesCompleted;
    
    /// <remarks/>
    public event getMonthlyAverageExchangeRatesCompletedEventHandler getMonthlyAverageExchangeRatesCompleted;
    
    /// <remarks/>
    public event getInterestAndExchangeGroupNamesCompletedEventHandler getInterestAndExchangeGroupNamesCompleted;
    
    /// <remarks/>
    public event getCrossRatesCompletedEventHandler getCrossRatesCompleted;
    
    /// <remarks/>
    public event getAllCrossNamesCompletedEventHandler getAllCrossNamesCompleted;
    
    /// <remarks/>
    public event getCalendarDaysCompletedEventHandler getCalendarDaysCompleted;
    
    /// <remarks/>
    public event getAnnualAverageExchangeRatesCompletedEventHandler getAnnualAverageExchangeRatesCompleted;
    
    /// <remarks/>
    public event getInterestAndExchangeRatesCompletedEventHandler getInterestAndExchangeRatesCompleted;
    
    /// <remarks/>
    public event getLatestInterestAndExchangeRatesCompletedEventHandler getLatestInterestAndExchangeRatesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getInterestAndExchangeNames", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public GroupSeries[] getInterestAndExchangeNames([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int groupid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] LanguageType languageid) {
        object[] results = this.Invoke("getInterestAndExchangeNames", new object[] {
                    groupid,
                    languageid});
        return ((GroupSeries[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetInterestAndExchangeNames(int groupid, LanguageType languageid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getInterestAndExchangeNames", new object[] {
                    groupid,
                    languageid}, callback, asyncState);
    }
    
    /// <remarks/>
    public GroupSeries[] EndgetInterestAndExchangeNames(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((GroupSeries[])(results[0]));
    }
    
    /// <remarks/>
    public void getInterestAndExchangeNamesAsync(int groupid, LanguageType languageid) {
        this.getInterestAndExchangeNamesAsync(groupid, languageid, null);
    }
    
    /// <remarks/>
    public void getInterestAndExchangeNamesAsync(int groupid, LanguageType languageid, object userState) {
        if ((this.getInterestAndExchangeNamesOperationCompleted == null)) {
            this.getInterestAndExchangeNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInterestAndExchangeNamesOperationCompleted);
        }
        this.InvokeAsync("getInterestAndExchangeNames", new object[] {
                    groupid,
                    languageid}, this.getInterestAndExchangeNamesOperationCompleted, userState);
    }
    
    private void OngetInterestAndExchangeNamesOperationCompleted(object arg) {
        if ((this.getInterestAndExchangeNamesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getInterestAndExchangeNamesCompleted(this, new getInterestAndExchangeNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getMonthlyAverageExchangeRates", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Result getMonthlyAverageExchangeRates([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int year, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int month, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] LanguageType languageid) {
        object[] results = this.Invoke("getMonthlyAverageExchangeRates", new object[] {
                    year,
                    month,
                    languageid});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetMonthlyAverageExchangeRates(int year, int month, LanguageType languageid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getMonthlyAverageExchangeRates", new object[] {
                    year,
                    month,
                    languageid}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndgetMonthlyAverageExchangeRates(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void getMonthlyAverageExchangeRatesAsync(int year, int month, LanguageType languageid) {
        this.getMonthlyAverageExchangeRatesAsync(year, month, languageid, null);
    }
    
    /// <remarks/>
    public void getMonthlyAverageExchangeRatesAsync(int year, int month, LanguageType languageid, object userState) {
        if ((this.getMonthlyAverageExchangeRatesOperationCompleted == null)) {
            this.getMonthlyAverageExchangeRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMonthlyAverageExchangeRatesOperationCompleted);
        }
        this.InvokeAsync("getMonthlyAverageExchangeRates", new object[] {
                    year,
                    month,
                    languageid}, this.getMonthlyAverageExchangeRatesOperationCompleted, userState);
    }
    
    private void OngetMonthlyAverageExchangeRatesOperationCompleted(object arg) {
        if ((this.getMonthlyAverageExchangeRatesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getMonthlyAverageExchangeRatesCompleted(this, new getMonthlyAverageExchangeRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getInterestAndExchangeGroupNames", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Group[] getInterestAndExchangeGroupNames([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] LanguageType languageid) {
        object[] results = this.Invoke("getInterestAndExchangeGroupNames", new object[] {
                    languageid});
        return ((Group[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetInterestAndExchangeGroupNames(LanguageType languageid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getInterestAndExchangeGroupNames", new object[] {
                    languageid}, callback, asyncState);
    }
    
    /// <remarks/>
    public Group[] EndgetInterestAndExchangeGroupNames(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Group[])(results[0]));
    }
    
    /// <remarks/>
    public void getInterestAndExchangeGroupNamesAsync(LanguageType languageid) {
        this.getInterestAndExchangeGroupNamesAsync(languageid, null);
    }
    
    /// <remarks/>
    public void getInterestAndExchangeGroupNamesAsync(LanguageType languageid, object userState) {
        if ((this.getInterestAndExchangeGroupNamesOperationCompleted == null)) {
            this.getInterestAndExchangeGroupNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInterestAndExchangeGroupNamesOperationCompleted);
        }
        this.InvokeAsync("getInterestAndExchangeGroupNames", new object[] {
                    languageid}, this.getInterestAndExchangeGroupNamesOperationCompleted, userState);
    }
    
    private void OngetInterestAndExchangeGroupNamesOperationCompleted(object arg) {
        if ((this.getInterestAndExchangeGroupNamesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getInterestAndExchangeGroupNamesCompleted(this, new getInterestAndExchangeGroupNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getCrossRates", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CrossResult getCrossRates([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] CrossRequestParameters crossRequestParameters) {
        object[] results = this.Invoke("getCrossRates", new object[] {
                    crossRequestParameters});
        return ((CrossResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCrossRates(CrossRequestParameters crossRequestParameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCrossRates", new object[] {
                    crossRequestParameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public CrossResult EndgetCrossRates(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CrossResult)(results[0]));
    }
    
    /// <remarks/>
    public void getCrossRatesAsync(CrossRequestParameters crossRequestParameters) {
        this.getCrossRatesAsync(crossRequestParameters, null);
    }
    
    /// <remarks/>
    public void getCrossRatesAsync(CrossRequestParameters crossRequestParameters, object userState) {
        if ((this.getCrossRatesOperationCompleted == null)) {
            this.getCrossRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCrossRatesOperationCompleted);
        }
        this.InvokeAsync("getCrossRates", new object[] {
                    crossRequestParameters}, this.getCrossRatesOperationCompleted, userState);
    }
    
    private void OngetCrossRatesOperationCompleted(object arg) {
        if ((this.getCrossRatesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCrossRatesCompleted(this, new getCrossRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getAllCrossNames", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Series[] getAllCrossNames([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] LanguageType languageid) {
        object[] results = this.Invoke("getAllCrossNames", new object[] {
                    languageid});
        return ((Series[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllCrossNames(LanguageType languageid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllCrossNames", new object[] {
                    languageid}, callback, asyncState);
    }
    
    /// <remarks/>
    public Series[] EndgetAllCrossNames(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Series[])(results[0]));
    }
    
    /// <remarks/>
    public void getAllCrossNamesAsync(LanguageType languageid) {
        this.getAllCrossNamesAsync(languageid, null);
    }
    
    /// <remarks/>
    public void getAllCrossNamesAsync(LanguageType languageid, object userState) {
        if ((this.getAllCrossNamesOperationCompleted == null)) {
            this.getAllCrossNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllCrossNamesOperationCompleted);
        }
        this.InvokeAsync("getAllCrossNames", new object[] {
                    languageid}, this.getAllCrossNamesOperationCompleted, userState);
    }
    
    private void OngetAllCrossNamesOperationCompleted(object arg) {
        if ((this.getAllCrossNamesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getAllCrossNamesCompleted(this, new getAllCrossNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getCalendarDays", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CalendarDay[] getCalendarDays([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime datefrom, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")] System.DateTime dateto) {
        object[] results = this.Invoke("getCalendarDays", new object[] {
                    datefrom,
                    dateto});
        return ((CalendarDay[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCalendarDays(System.DateTime datefrom, System.DateTime dateto, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCalendarDays", new object[] {
                    datefrom,
                    dateto}, callback, asyncState);
    }
    
    /// <remarks/>
    public CalendarDay[] EndgetCalendarDays(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CalendarDay[])(results[0]));
    }
    
    /// <remarks/>
    public void getCalendarDaysAsync(System.DateTime datefrom, System.DateTime dateto) {
        this.getCalendarDaysAsync(datefrom, dateto, null);
    }
    
    /// <remarks/>
    public void getCalendarDaysAsync(System.DateTime datefrom, System.DateTime dateto, object userState) {
        if ((this.getCalendarDaysOperationCompleted == null)) {
            this.getCalendarDaysOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCalendarDaysOperationCompleted);
        }
        this.InvokeAsync("getCalendarDays", new object[] {
                    datefrom,
                    dateto}, this.getCalendarDaysOperationCompleted, userState);
    }
    
    private void OngetCalendarDaysOperationCompleted(object arg) {
        if ((this.getCalendarDaysCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCalendarDaysCompleted(this, new getCalendarDaysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getAnnualAverageExchangeRates", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Result getAnnualAverageExchangeRates([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int year, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int month, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] LanguageType languageid) {
        object[] results = this.Invoke("getAnnualAverageExchangeRates", new object[] {
                    year,
                    month,
                    languageid});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAnnualAverageExchangeRates(int year, int month, LanguageType languageid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAnnualAverageExchangeRates", new object[] {
                    year,
                    month,
                    languageid}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndgetAnnualAverageExchangeRates(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void getAnnualAverageExchangeRatesAsync(int year, int month, LanguageType languageid) {
        this.getAnnualAverageExchangeRatesAsync(year, month, languageid, null);
    }
    
    /// <remarks/>
    public void getAnnualAverageExchangeRatesAsync(int year, int month, LanguageType languageid, object userState) {
        if ((this.getAnnualAverageExchangeRatesOperationCompleted == null)) {
            this.getAnnualAverageExchangeRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAnnualAverageExchangeRatesOperationCompleted);
        }
        this.InvokeAsync("getAnnualAverageExchangeRates", new object[] {
                    year,
                    month,
                    languageid}, this.getAnnualAverageExchangeRatesOperationCompleted, userState);
    }
    
    private void OngetAnnualAverageExchangeRatesOperationCompleted(object arg) {
        if ((this.getAnnualAverageExchangeRatesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getAnnualAverageExchangeRatesCompleted(this, new getAnnualAverageExchangeRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getInterestAndExchangeRates", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Result getInterestAndExchangeRates([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] SearchRequestParameters searchRequestParameters) {
        object[] results = this.Invoke("getInterestAndExchangeRates", new object[] {
                    searchRequestParameters});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetInterestAndExchangeRates(SearchRequestParameters searchRequestParameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getInterestAndExchangeRates", new object[] {
                    searchRequestParameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndgetInterestAndExchangeRates(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void getInterestAndExchangeRatesAsync(SearchRequestParameters searchRequestParameters) {
        this.getInterestAndExchangeRatesAsync(searchRequestParameters, null);
    }
    
    /// <remarks/>
    public void getInterestAndExchangeRatesAsync(SearchRequestParameters searchRequestParameters, object userState) {
        if ((this.getInterestAndExchangeRatesOperationCompleted == null)) {
            this.getInterestAndExchangeRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInterestAndExchangeRatesOperationCompleted);
        }
        this.InvokeAsync("getInterestAndExchangeRates", new object[] {
                    searchRequestParameters}, this.getInterestAndExchangeRatesOperationCompleted, userState);
    }
    
    private void OngetInterestAndExchangeRatesOperationCompleted(object arg) {
        if ((this.getInterestAndExchangeRatesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getInterestAndExchangeRatesCompleted(this, new getInterestAndExchangeRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getLatestInterestAndExchangeRates", RequestNamespace="http://swea.riksbank.se/xsd", ResponseNamespace="http://swea.riksbank.se/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public Result getLatestInterestAndExchangeRates([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] LanguageType languageid, [System.Xml.Serialization.XmlElementAttribute("seriesid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] seriesid) {
        object[] results = this.Invoke("getLatestInterestAndExchangeRates", new object[] {
                    languageid,
                    seriesid});
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetLatestInterestAndExchangeRates(LanguageType languageid, string[] seriesid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getLatestInterestAndExchangeRates", new object[] {
                    languageid,
                    seriesid}, callback, asyncState);
    }
    
    /// <remarks/>
    public Result EndgetLatestInterestAndExchangeRates(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Result)(results[0]));
    }
    
    /// <remarks/>
    public void getLatestInterestAndExchangeRatesAsync(LanguageType languageid, string[] seriesid) {
        this.getLatestInterestAndExchangeRatesAsync(languageid, seriesid, null);
    }
    
    /// <remarks/>
    public void getLatestInterestAndExchangeRatesAsync(LanguageType languageid, string[] seriesid, object userState) {
        if ((this.getLatestInterestAndExchangeRatesOperationCompleted == null)) {
            this.getLatestInterestAndExchangeRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLatestInterestAndExchangeRatesOperationCompleted);
        }
        this.InvokeAsync("getLatestInterestAndExchangeRates", new object[] {
                    languageid,
                    seriesid}, this.getLatestInterestAndExchangeRatesOperationCompleted, userState);
    }
    
    private void OngetLatestInterestAndExchangeRatesOperationCompleted(object arg) {
        if ((this.getLatestInterestAndExchangeRatesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getLatestInterestAndExchangeRatesCompleted(this, new getLatestInterestAndExchangeRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public enum LanguageType {
    
    /// <remarks/>
    en,
    
    /// <remarks/>
    sv,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class GroupSeries {
    
    private System.Nullable<System.DateTime> datefromField;
    
    private bool datefromFieldSpecified;
    
    private System.Nullable<System.DateTime> datetoField;
    
    private bool datetoFieldSpecified;
    
    private string descriptionField;
    
    private string groupidField;
    
    private string longdescriptionField;
    
    private string seriesidField;
    
    private string shortdescriptionField;
    
    private string sourceField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> datefrom {
        get {
            return this.datefromField;
        }
        set {
            this.datefromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datefromSpecified {
        get {
            return this.datefromFieldSpecified;
        }
        set {
            this.datefromFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> dateto {
        get {
            return this.datetoField;
        }
        set {
            this.datetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datetoSpecified {
        get {
            return this.datetoFieldSpecified;
        }
        set {
            this.datetoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string groupid {
        get {
            return this.groupidField;
        }
        set {
            this.groupidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string longdescription {
        get {
            return this.longdescriptionField;
        }
        set {
            this.longdescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string seriesid {
        get {
            return this.seriesidField;
        }
        set {
            this.seriesidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string shortdescription {
        get {
            return this.shortdescriptionField;
        }
        set {
            this.shortdescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class SearchGroupSeries {
    
    private string groupidField;
    
    private string seriesidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string groupid {
        get {
            return this.groupidField;
        }
        set {
            this.groupidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seriesid {
        get {
            return this.seriesidField;
        }
        set {
            this.seriesidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class SearchRequestParameters {
    
    private AggregateMethodType aggregateMethodField;
    
    private System.DateTime datefromField;
    
    private System.DateTime datetoField;
    
    private LanguageType languageidField;
    
    private bool minField;
    
    private bool avgField;
    
    private bool maxField;
    
    private bool ultimoField;
    
    private SearchGroupSeries[] searchGroupSeriesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AggregateMethodType aggregateMethod {
        get {
            return this.aggregateMethodField;
        }
        set {
            this.aggregateMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime datefrom {
        get {
            return this.datefromField;
        }
        set {
            this.datefromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime dateto {
        get {
            return this.datetoField;
        }
        set {
            this.datetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public LanguageType languageid {
        get {
            return this.languageidField;
        }
        set {
            this.languageidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool avg {
        get {
            return this.avgField;
        }
        set {
            this.avgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ultimo {
        get {
            return this.ultimoField;
        }
        set {
            this.ultimoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("searchGroupSeries", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SearchGroupSeries[] searchGroupSeries {
        get {
            return this.searchGroupSeriesField;
        }
        set {
            this.searchGroupSeriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public enum AggregateMethodType {
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    W,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    Q,
    
    /// <remarks/>
    Y,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class CalendarDay {
    
    private string bankdayField;
    
    private System.Nullable<System.DateTime> caldateField;
    
    private string weekField;
    
    private int weekyearField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string bankday {
        get {
            return this.bankdayField;
        }
        set {
            this.bankdayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> caldate {
        get {
            return this.caldateField;
        }
        set {
            this.caldateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string week {
        get {
            return this.weekField;
        }
        set {
            this.weekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int weekyear {
        get {
            return this.weekyearField;
        }
        set {
            this.weekyearField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class Series {
    
    private System.Nullable<System.DateTime> datefromField;
    
    private bool datefromFieldSpecified;
    
    private System.Nullable<System.DateTime> datetoField;
    
    private bool datetoFieldSpecified;
    
    private string seriesdescriptionField;
    
    private string seriesidField;
    
    private string seriesnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> datefrom {
        get {
            return this.datefromField;
        }
        set {
            this.datefromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datefromSpecified {
        get {
            return this.datefromFieldSpecified;
        }
        set {
            this.datefromFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> dateto {
        get {
            return this.datetoField;
        }
        set {
            this.datetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datetoSpecified {
        get {
            return this.datetoFieldSpecified;
        }
        set {
            this.datetoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seriesdescription {
        get {
            return this.seriesdescriptionField;
        }
        set {
            this.seriesdescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seriesid {
        get {
            return this.seriesidField;
        }
        set {
            this.seriesidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seriesname {
        get {
            return this.seriesnameField;
        }
        set {
            this.seriesnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class CrossResultSeries {
    
    private string seriesid1Field;
    
    private string seriesid2Field;
    
    private string seriesnameField;
    
    private ResultRow[] resultrowsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string seriesid1 {
        get {
            return this.seriesid1Field;
        }
        set {
            this.seriesid1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string seriesid2 {
        get {
            return this.seriesid2Field;
        }
        set {
            this.seriesid2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string seriesname {
        get {
            return this.seriesnameField;
        }
        set {
            this.seriesnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("resultrows", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public ResultRow[] resultrows {
        get {
            return this.resultrowsField;
        }
        set {
            this.resultrowsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class ResultRow {
    
    private System.Nullable<System.DateTime> dateField;
    
    private bool dateFieldSpecified;
    
    private string periodField;
    
    private System.Nullable<double> minField;
    
    private bool minFieldSpecified;
    
    private System.Nullable<double> averageField;
    
    private bool averageFieldSpecified;
    
    private System.Nullable<double> maxField;
    
    private bool maxFieldSpecified;
    
    private System.Nullable<double> ultimoField;
    
    private bool ultimoFieldSpecified;
    
    private System.Nullable<double> valueField;
    
    private bool valueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateSpecified {
        get {
            return this.dateFieldSpecified;
        }
        set {
            this.dateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<double> min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minSpecified {
        get {
            return this.minFieldSpecified;
        }
        set {
            this.minFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<double> average {
        get {
            return this.averageField;
        }
        set {
            this.averageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageSpecified {
        get {
            return this.averageFieldSpecified;
        }
        set {
            this.averageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<double> max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxSpecified {
        get {
            return this.maxFieldSpecified;
        }
        set {
            this.maxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<double> ultimo {
        get {
            return this.ultimoField;
        }
        set {
            this.ultimoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ultimoSpecified {
        get {
            return this.ultimoFieldSpecified;
        }
        set {
            this.ultimoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<double> value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class CrossResultGroup {
    
    private string groupidField;
    
    private string groupnameField;
    
    private CrossResultSeries[] seriesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string groupid {
        get {
            return this.groupidField;
        }
        set {
            this.groupidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string groupname {
        get {
            return this.groupnameField;
        }
        set {
            this.groupnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("series", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CrossResultSeries[] series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class CrossResult {
    
    private System.Nullable<System.DateTime> datefromField;
    
    private bool datefromFieldSpecified;
    
    private System.Nullable<System.DateTime> datetoField;
    
    private bool datetoFieldSpecified;
    
    private string informationtextField;
    
    private CrossResultGroup[] groupsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> datefrom {
        get {
            return this.datefromField;
        }
        set {
            this.datefromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datefromSpecified {
        get {
            return this.datefromFieldSpecified;
        }
        set {
            this.datefromFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> dateto {
        get {
            return this.datetoField;
        }
        set {
            this.datetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datetoSpecified {
        get {
            return this.datetoFieldSpecified;
        }
        set {
            this.datetoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string informationtext {
        get {
            return this.informationtextField;
        }
        set {
            this.informationtextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("groups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public CrossResultGroup[] groups {
        get {
            return this.groupsField;
        }
        set {
            this.groupsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class CurrencyCrossPair {
    
    private string seriesid1Field;
    
    private string seriesid2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seriesid1 {
        get {
            return this.seriesid1Field;
        }
        set {
            this.seriesid1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seriesid2 {
        get {
            return this.seriesid2Field;
        }
        set {
            this.seriesid2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class CrossRequestParameters {
    
    private AggregateMethodType aggregateMethodField;
    
    private CurrencyCrossPair[] crossPairField;
    
    private System.Nullable<System.DateTime> datefromField;
    
    private System.Nullable<System.DateTime> datetoField;
    
    private System.Nullable<LanguageType> languageidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AggregateMethodType aggregateMethod {
        get {
            return this.aggregateMethodField;
        }
        set {
            this.aggregateMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("crossPair", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CurrencyCrossPair[] crossPair {
        get {
            return this.crossPairField;
        }
        set {
            this.crossPairField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> datefrom {
        get {
            return this.datefromField;
        }
        set {
            this.datefromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> dateto {
        get {
            return this.datetoField;
        }
        set {
            this.datetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<LanguageType> languageid {
        get {
            return this.languageidField;
        }
        set {
            this.languageidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class Group {
    
    private string groupdescriptionField;
    
    private int groupidField;
    
    private bool groupidFieldSpecified;
    
    private string groupnameField;
    
    private string languageidField;
    
    private System.Nullable<int> parentgroupidField;
    
    private bool parentgroupidFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string groupdescription {
        get {
            return this.groupdescriptionField;
        }
        set {
            this.groupdescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int groupid {
        get {
            return this.groupidField;
        }
        set {
            this.groupidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool groupidSpecified {
        get {
            return this.groupidFieldSpecified;
        }
        set {
            this.groupidFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string groupname {
        get {
            return this.groupnameField;
        }
        set {
            this.groupnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string languageid {
        get {
            return this.languageidField;
        }
        set {
            this.languageidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> parentgroupid {
        get {
            return this.parentgroupidField;
        }
        set {
            this.parentgroupidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool parentgroupidSpecified {
        get {
            return this.parentgroupidFieldSpecified;
        }
        set {
            this.parentgroupidFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class ResultSeries {
    
    private string seriesidField;
    
    private string seriesnameField;
    
    private System.Nullable<double> unitField;
    
    private bool unitFieldSpecified;
    
    private ResultRow[] resultrowsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string seriesid {
        get {
            return this.seriesidField;
        }
        set {
            this.seriesidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string seriesname {
        get {
            return this.seriesnameField;
        }
        set {
            this.seriesnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<double> unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool unitSpecified {
        get {
            return this.unitFieldSpecified;
        }
        set {
            this.unitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("resultrows", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public ResultRow[] resultrows {
        get {
            return this.resultrowsField;
        }
        set {
            this.resultrowsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class ResultGroup {
    
    private string groupidField;
    
    private string groupnameField;
    
    private ResultSeries[] seriesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string groupid {
        get {
            return this.groupidField;
        }
        set {
            this.groupidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string groupname {
        get {
            return this.groupnameField;
        }
        set {
            this.groupnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("series", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public ResultSeries[] series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://swea.riksbank.se/xsd")]
public partial class Result {
    
    private System.Nullable<System.DateTime> datefromField;
    
    private bool datefromFieldSpecified;
    
    private System.Nullable<System.DateTime> datetoField;
    
    private bool datetoFieldSpecified;
    
    private string informationtextField;
    
    private ResultGroup[] groupsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> datefrom {
        get {
            return this.datefromField;
        }
        set {
            this.datefromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datefromSpecified {
        get {
            return this.datefromFieldSpecified;
        }
        set {
            this.datefromFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> dateto {
        get {
            return this.datetoField;
        }
        set {
            this.datetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool datetoSpecified {
        get {
            return this.datetoFieldSpecified;
        }
        set {
            this.datetoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string informationtext {
        get {
            return this.informationtextField;
        }
        set {
            this.informationtextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("groups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public ResultGroup[] groups {
        get {
            return this.groupsField;
        }
        set {
            this.groupsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getInterestAndExchangeNamesCompletedEventHandler(object sender, getInterestAndExchangeNamesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getInterestAndExchangeNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getInterestAndExchangeNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public GroupSeries[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((GroupSeries[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getMonthlyAverageExchangeRatesCompletedEventHandler(object sender, getMonthlyAverageExchangeRatesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getMonthlyAverageExchangeRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getMonthlyAverageExchangeRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getInterestAndExchangeGroupNamesCompletedEventHandler(object sender, getInterestAndExchangeGroupNamesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getInterestAndExchangeGroupNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getInterestAndExchangeGroupNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Group[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Group[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getCrossRatesCompletedEventHandler(object sender, getCrossRatesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCrossRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCrossRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CrossResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CrossResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getAllCrossNamesCompletedEventHandler(object sender, getAllCrossNamesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getAllCrossNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getAllCrossNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Series[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Series[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getCalendarDaysCompletedEventHandler(object sender, getCalendarDaysCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCalendarDaysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCalendarDaysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CalendarDay[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CalendarDay[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getAnnualAverageExchangeRatesCompletedEventHandler(object sender, getAnnualAverageExchangeRatesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getAnnualAverageExchangeRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getAnnualAverageExchangeRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getInterestAndExchangeRatesCompletedEventHandler(object sender, getInterestAndExchangeRatesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getInterestAndExchangeRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getInterestAndExchangeRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getLatestInterestAndExchangeRatesCompletedEventHandler(object sender, getLatestInterestAndExchangeRatesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getLatestInterestAndExchangeRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getLatestInterestAndExchangeRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Result)(this.results[0]));
        }
    }
}
